<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('country')->insert(['code' => 'AF', 'name' => 'AFGHANISTAN']);
        DB::table('country')->insert(['code' => 'AL', 'name' => 'ALBANIA']);
        DB::table('country')->insert(['code' => 'DZ', 'name' => 'ALGERIA']);
        DB::table('country')->insert(['code' => 'AS', 'name' => 'AMERICAN SAMOA']);
        DB::table('country')->insert(['code' => 'AD', 'name' => 'ANDORRA']);
        DB::table('country')->insert(['code' => 'AO', 'name' => 'ANGOLA']);
        DB::table('country')->insert(['code' => 'AI', 'name' => 'ANGUILLA']);
        DB::table('country')->insert(['code' => 'AQ', 'name' => 'ANTARCTICA']);
        DB::table('country')->insert(['code' => 'AG', 'name' => 'ANTIGUA AND BARBUDA']);
        DB::table('country')->insert(['code' => 'AR', 'name' => 'ARGENTINA']);
        DB::table('country')->insert(['code' => 'AM', 'name' => 'ARMENIA']);
        DB::table('country')->insert(['code' => 'AW', 'name' => 'ARUBA']);
        DB::table('country')->insert(['code' => 'AU', 'name' => 'AUSTRALIA']);
        DB::table('country')->insert(['code' => 'AT', 'name' => 'AUSTRIA']);
        DB::table('country')->insert(['code' => 'AZ', 'name' => 'AZERBAIJAN']);
        DB::table('country')->insert(['code' => 'BS', 'name' => 'BAHAMAS']);
        DB::table('country')->insert(['code' => 'BH', 'name' => 'BAHRAIN']);
        DB::table('country')->insert(['code' => 'BD', 'name' => 'BANGLADESH']);
        DB::table('country')->insert(['code' => 'BB', 'name' => 'BARBADOS']);
        DB::table('country')->insert(['code' => 'BY', 'name' => 'BELARUS']);
        DB::table('country')->insert(['code' => 'BE', 'name' => 'BELGIUM']);
        DB::table('country')->insert(['code' => 'BZ', 'name' => 'BELIZE']);
        DB::table('country')->insert(['code' => 'BJ', 'name' => 'BENIN']);
        DB::table('country')->insert(['code' => 'BM', 'name' => 'BERMUDA']);
        DB::table('country')->insert(['code' => 'BT', 'name' => 'BHUTAN']);
        DB::table('country')->insert(['code' => 'BO', 'name' => 'BOLIVIA']);
        DB::table('country')->insert(['code' => 'BA', 'name' => 'BOSNIA AND HERZEGOVINA']);
        DB::table('country')->insert(['code' => 'BW', 'name' => 'BOTSWANA']);
        DB::table('country')->insert(['code' => 'BV', 'name' => 'BOUVET ISLAND']);
        DB::table('country')->insert(['code' => 'BR', 'name' => 'BRAZIL']);
        DB::table('country')->insert(['code' => 'IO', 'name' => 'BRITISH INDIAN OCEAN TERRITORY']);
        DB::table('country')->insert(['code' => 'BN', 'name' => 'BRUNEI DARUSSALAM']);
        DB::table('country')->insert(['code' => 'BG', 'name' => 'BULGARIA']);
        DB::table('country')->insert(['code' => 'BF', 'name' => 'BURKINA FASO']);
        DB::table('country')->insert(['code' => 'BI', 'name' => 'BURUNDI']);
        DB::table('country')->insert(['code' => 'KH', 'name' => 'CAMBODIA']);
        DB::table('country')->insert(['code' => 'CM', 'name' => 'CAMEROON']);
        DB::table('country')->insert(['code' => 'CA', 'name' => 'CANADA']);
        DB::table('country')->insert(['code' => 'CV', 'name' => 'CAPE VERDE']);
        DB::table('country')->insert(['code' => 'KY', 'name' => 'CAYMAN ISLANDS']);
        DB::table('country')->insert(['code' => 'CF', 'name' => 'CENTRAL AFRICAN REPUBLIC']);
        DB::table('country')->insert(['code' => 'TD', 'name' => 'CHAD']);
        DB::table('country')->insert(['code' => 'CL', 'name' => 'CHILE']);
        DB::table('country')->insert(['code' => 'CN', 'name' => 'CHINA']);
        DB::table('country')->insert(['code' => 'CX', 'name' => 'CHRISTMAS ISLAND']);
        DB::table('country')->insert(['code' => 'CC', 'name' => 'COCOS (KEELING) ISLANDS']);
        DB::table('country')->insert(['code' => 'CO', 'name' => 'COLOMBIA']);
        DB::table('country')->insert(['code' => 'KM', 'name' => 'COMOROS']);
        DB::table('country')->insert(['code' => 'CG', 'name' => 'CONGO']);
        DB::table('country')->insert(['code' => 'CD', 'name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE']);
        DB::table('country')->insert(['code' => 'CK', 'name' => 'COOK ISLANDS']);
        DB::table('country')->insert(['code' => 'CR', 'name' => 'COSTA RICA']);
        DB::table('country')->insert(['code' => 'CI', 'name' => 'COTE D\'IVOIRE']);
        DB::table('country')->insert(['code' => 'HR', 'name' => 'CROATIA']);
        DB::table('country')->insert(['code' => 'CU', 'name' => 'CUBA']);
        DB::table('country')->insert(['code' => 'CY', 'name' => 'CYPRUS']);
        DB::table('country')->insert(['code' => 'CZ', 'name' => 'CZECH REPUBLIC']);
        DB::table('country')->insert(['code' => 'DK', 'name' => 'DENMARK']);
        DB::table('country')->insert(['code' => 'DJ', 'name' => 'DJIBOUTI']);
        DB::table('country')->insert(['code' => 'DM', 'name' => 'DOMINICA']);
        DB::table('country')->insert(['code' => 'DO', 'name' => 'DOMINICAN REPUBLIC']);
        DB::table('country')->insert(['code' => 'EC', 'name' => 'ECUADOR']);
        DB::table('country')->insert(['code' => 'EG', 'name' => 'EGYPT']);
        DB::table('country')->insert(['code' => 'SV', 'name' => 'EL SALVADOR']);
        DB::table('country')->insert(['code' => 'GQ', 'name' => 'EQUATORIAL GUINEA']);
        DB::table('country')->insert(['code' => 'ER', 'name' => 'ERITREA']);
        DB::table('country')->insert(['code' => 'EE', 'name' => 'ESTONIA']);
        DB::table('country')->insert(['code' => 'ET', 'name' => 'ETHIOPIA']);
        DB::table('country')->insert(['code' => 'FK', 'name' => 'FALKLAND ISLANDS (MALVINAS)']);
        DB::table('country')->insert(['code' => 'FO', 'name' => 'FAROE ISLANDS']);
        DB::table('country')->insert(['code' => 'FJ', 'name' => 'FIJI']);
        DB::table('country')->insert(['code' => 'FI', 'name' => 'FINLAND']);
        DB::table('country')->insert(['code' => 'FR', 'name' => 'FRANCE']);
        DB::table('country')->insert(['code' => 'GF', 'name' => 'FRENCH GUIANA']);
        DB::table('country')->insert(['code' => 'PF', 'name' => 'FRENCH POLYNESIA']);
        DB::table('country')->insert(['code' => 'TF', 'name' => 'FRENCH SOUTHERN TERRITORIES']);
        DB::table('country')->insert(['code' => 'GA', 'name' => 'GABON']);
        DB::table('country')->insert(['code' => 'GM', 'name' => 'GAMBIA']);
        DB::table('country')->insert(['code' => 'GE', 'name' => 'GEORGIA']);
        DB::table('country')->insert(['code' => 'DE', 'name' => 'GERMANY']);
        DB::table('country')->insert(['code' => 'GH', 'name' => 'GHANA']);
        DB::table('country')->insert(['code' => 'GI', 'name' => 'GIBRALTAR']);
        DB::table('country')->insert(['code' => 'GR', 'name' => 'GREECE']);
        DB::table('country')->insert(['code' => 'GL', 'name' => 'GREENLAND']);
        DB::table('country')->insert(['code' => 'GD', 'name' => 'GRENADA']);
        DB::table('country')->insert(['code' => 'GP', 'name' => 'GUADELOUPE']);
        DB::table('country')->insert(['code' => 'GU', 'name' => 'GUAM']);
        DB::table('country')->insert(['code' => 'GT', 'name' => 'GUATEMALA']);
        DB::table('country')->insert(['code' => 'GN', 'name' => 'GUINEA']);
        DB::table('country')->insert(['code' => 'GW', 'name' => 'GUINEA-BISSAU']);
        DB::table('country')->insert(['code' => 'GY', 'name' => 'GUYANA']);
        DB::table('country')->insert(['code' => 'HT', 'name' => 'HAITI']);
        DB::table('country')->insert(['code' => 'HM', 'name' => 'HEARD ISLAND AND MCDONALD ISLANDS']);
        DB::table('country')->insert(['code' => 'VA', 'name' => 'HOLY SEE (VATICAN CITY STATE)']);
        DB::table('country')->insert(['code' => 'HN', 'name' => 'HONDURAS']);
        DB::table('country')->insert(['code' => 'HK', 'name' => 'HONG KONG']);
        DB::table('country')->insert(['code' => 'HU', 'name' => 'HUNGARY']);
        DB::table('country')->insert(['code' => 'IS', 'name' => 'ICELAND']);
        DB::table('country')->insert(['code' => 'IN', 'name' => 'INDIA']);
        DB::table('country')->insert(['code' => 'ID', 'name' => 'INDONESIA']);
        DB::table('country')->insert(['code' => 'IR', 'name' => 'IRAN, ISLAMIC REPUBLIC OF']);
        DB::table('country')->insert(['code' => 'IQ', 'name' => 'IRAQ']);
        DB::table('country')->insert(['code' => 'IE', 'name' => 'IRELAND']);
        DB::table('country')->insert(['code' => 'IL', 'name' => 'ISRAEL']);
        DB::table('country')->insert(['code' => 'IT', 'name' => 'ITALY']);
        DB::table('country')->insert(['code' => 'JM', 'name' => 'JAMAICA']);
        DB::table('country')->insert(['code' => 'JP', 'name' => 'JAPAN']);
        DB::table('country')->insert(['code' => 'JO', 'name' => 'JORDAN']);
        DB::table('country')->insert(['code' => 'KZ', 'name' => 'KAZAKHSTAN']);
        DB::table('country')->insert(['code' => 'KE', 'name' => 'KENYA']);
        DB::table('country')->insert(['code' => 'KI', 'name' => 'KIRIBATI']);
        DB::table('country')->insert(['code' => 'KP', 'name' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF']);
        DB::table('country')->insert(['code' => 'KR', 'name' => 'KOREA, REPUBLIC OF']);
        DB::table('country')->insert(['code' => 'KW', 'name' => 'KUWAIT']);
        DB::table('country')->insert(['code' => 'KG', 'name' => 'KYRGYZSTAN']);
        DB::table('country')->insert(['code' => 'LA', 'name' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC']);
        DB::table('country')->insert(['code' => 'LV', 'name' => 'LATVIA']);
        DB::table('country')->insert(['code' => 'LB', 'name' => 'LEBANON']);
        DB::table('country')->insert(['code' => 'LS', 'name' => 'LESOTHO']);
        DB::table('country')->insert(['code' => 'LR', 'name' => 'LIBERIA']);
        DB::table('country')->insert(['code' => 'LY', 'name' => 'LIBYAN ARAB JAMAHIRIYA']);
        DB::table('country')->insert(['code' => 'LI', 'name' => 'LIECHTENSTEIN']);
        DB::table('country')->insert(['code' => 'LT', 'name' => 'LITHUANIA']);
        DB::table('country')->insert(['code' => 'LU', 'name' => 'LUXEMBOURG']);
        DB::table('country')->insert(['code' => 'MO', 'name' => 'MACAO']);
        DB::table('country')->insert(['code' => 'MK', 'name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF']);
        DB::table('country')->insert(['code' => 'MG', 'name' => 'MADAGASCAR']);
        DB::table('country')->insert(['code' => 'MW', 'name' => 'MALAWI']);
        DB::table('country')->insert(['code' => 'MY', 'name' => 'MALAYSIA']);
        DB::table('country')->insert(['code' => 'MV', 'name' => 'MALDIVES']);
        DB::table('country')->insert(['code' => 'ML', 'name' => 'MALI']);
        DB::table('country')->insert(['code' => 'MT', 'name' => 'MALTA']);
        DB::table('country')->insert(['code' => 'MH', 'name' => 'MARSHALL ISLANDS']);
        DB::table('country')->insert(['code' => 'MQ', 'name' => 'MARTINIQUE']);
        DB::table('country')->insert(['code' => 'MR', 'name' => 'MAURITANIA']);
        DB::table('country')->insert(['code' => 'MU', 'name' => 'MAURITIUS']);
        DB::table('country')->insert(['code' => 'YT', 'name' => 'MAYOTTE']);
        DB::table('country')->insert(['code' => 'MX', 'name' => 'MEXICO']);
        DB::table('country')->insert(['code' => 'FM', 'name' => 'MICRONESIA, FEDERATED STATES OF']);
        DB::table('country')->insert(['code' => 'MD', 'name' => 'MOLDOVA, REPUBLIC OF']);
        DB::table('country')->insert(['code' => 'MC', 'name' => 'MONACO']);
        DB::table('country')->insert(['code' => 'MN', 'name' => 'MONGOLIA']);
        DB::table('country')->insert(['code' => 'MS', 'name' => 'MONTSERRAT']);
        DB::table('country')->insert(['code' => 'MA', 'name' => 'MOROCCO']);
        DB::table('country')->insert(['code' => 'MZ', 'name' => 'MOZAMBIQUE']);
        DB::table('country')->insert(['code' => 'MM', 'name' => 'MYANMAR']);
        DB::table('country')->insert(['code' => 'NA', 'name' => 'NAMIBIA']);
        DB::table('country')->insert(['code' => 'NR', 'name' => 'NAURU']);
        DB::table('country')->insert(['code' => 'NP', 'name' => 'NEPAL']);
        DB::table('country')->insert(['code' => 'NL', 'name' => 'NETHERLANDS']);
        DB::table('country')->insert(['code' => 'AN', 'name' => 'NETHERLANDS ANTILLES']);
        DB::table('country')->insert(['code' => 'NC', 'name' => 'NEW CALEDONIA']);
        DB::table('country')->insert(['code' => 'NZ', 'name' => 'NEW ZEALAND']);
        DB::table('country')->insert(['code' => 'NI', 'name' => 'NICARAGUA']);
        DB::table('country')->insert(['code' => 'NE', 'name' => 'NIGER']);
        DB::table('country')->insert(['code' => 'NG', 'name' => 'NIGERIA']);
        DB::table('country')->insert(['code' => 'NU', 'name' => 'NIUE']);
        DB::table('country')->insert(['code' => 'NF', 'name' => 'NORFOLK ISLAND']);
        DB::table('country')->insert(['code' => 'MP', 'name' => 'NORTHERN MARIANA ISLANDS']);
        DB::table('country')->insert(['code' => 'NO', 'name' => 'NORWAY']);
        DB::table('country')->insert(['code' => 'OM', 'name' => 'OMAN']);
        DB::table('country')->insert(['code' => 'PK', 'name' => 'PAKISTAN']);
        DB::table('country')->insert(['code' => 'PW', 'name' => 'PALAU']);
        DB::table('country')->insert(['code' => 'PS', 'name' => 'PALESTINIAN TERRITORY, OCCUPIED']);
        DB::table('country')->insert(['code' => 'PA', 'name' => 'PANAMA']);
        DB::table('country')->insert(['code' => 'PG', 'name' => 'PAPUA NEW GUINEA']);
        DB::table('country')->insert(['code' => 'PY', 'name' => 'PARAGUAY']);
        DB::table('country')->insert(['code' => 'PE', 'name' => 'PERU']);
        DB::table('country')->insert(['code' => 'PH', 'name' => 'PHILIPPINES']);
        DB::table('country')->insert(['code' => 'PN', 'name' => 'PITCAIRN']);
        DB::table('country')->insert(['code' => 'PL', 'name' => 'POLAND']);
        DB::table('country')->insert(['code' => 'PT', 'name' => 'PORTUGAL']);
        DB::table('country')->insert(['code' => 'PR', 'name' => 'PUERTO RICO']);
        DB::table('country')->insert(['code' => 'QA', 'name' => 'QATAR']);
        DB::table('country')->insert(['code' => 'RE', 'name' => 'REUNION']);
        DB::table('country')->insert(['code' => 'RO', 'name' => 'ROMANIA']);
        DB::table('country')->insert(['code' => 'RU', 'name' => 'RUSSIAN FEDERATION']);
        DB::table('country')->insert(['code' => 'RW', 'name' => 'RWANDA']);
        DB::table('country')->insert(['code' => 'SH', 'name' => 'SAINT HELENA']);
        DB::table('country')->insert(['code' => 'KN', 'name' => 'SAINT KITTS AND NEVIS']);
        DB::table('country')->insert(['code' => 'LC', 'name' => 'SAINT LUCIA']);
        DB::table('country')->insert(['code' => 'PM', 'name' => 'SAINT PIERRE AND MIQUELON']);
        DB::table('country')->insert(['code' => 'VC', 'name' => 'SAINT VINCENT AND THE GRENADINES']);
        DB::table('country')->insert(['code' => 'WS', 'name' => 'SAMOA']);
        DB::table('country')->insert(['code' => 'SM', 'name' => 'SAN MARINO']);
        DB::table('country')->insert(['code' => 'ST', 'name' => 'SAO TOME AND PRINCIPE']);
        DB::table('country')->insert(['code' => 'SA', 'name' => 'SAUDI ARABIA']);
        DB::table('country')->insert(['code' => 'SN', 'name' => 'SENEGAL']);
        DB::table('country')->insert(['code' => 'CS', 'name' => 'SERBIA AND MONTENEGRO']);
        DB::table('country')->insert(['code' => 'SC', 'name' => 'SEYCHELLES']);
        DB::table('country')->insert(['code' => 'SL', 'name' => 'SIERRA LEONE']);
        DB::table('country')->insert(['code' => 'SG', 'name' => 'SINGAPORE']);
        DB::table('country')->insert(['code' => 'SK', 'name' => 'SLOVAKIA']);
        DB::table('country')->insert(['code' => 'SI', 'name' => 'SLOVENIA']);
        DB::table('country')->insert(['code' => 'SB', 'name' => 'SOLOMON ISLANDS']);
        DB::table('country')->insert(['code' => 'SO', 'name' => 'SOMALIA']);
        DB::table('country')->insert(['code' => 'ZA', 'name' => 'SOUTH AFRICA']);
        DB::table('country')->insert(['code' => 'GS', 'name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS']);
        DB::table('country')->insert(['code' => 'ES', 'name' => 'SPAIN']);
        DB::table('country')->insert(['code' => 'LK', 'name' => 'SRI LANKA']);
        DB::table('country')->insert(['code' => 'SD', 'name' => 'SUDAN']);
        DB::table('country')->insert(['code' => 'SR', 'name' => 'SURIcode']);
        DB::table('country')->insert(['code' => 'SJ', 'name' => 'SVALBARD AND JAN MAYEN']);
        DB::table('country')->insert(['code' => 'SZ', 'name' => 'SWAZILAND']);
        DB::table('country')->insert(['code' => 'SE', 'name' => 'SWEDEN']);
        DB::table('country')->insert(['code' => 'CH', 'name' => 'SWITZERLAND']);
        DB::table('country')->insert(['code' => 'SY', 'name' => 'SYRIAN ARAB REPUBLIC']);
        DB::table('country')->insert(['code' => 'TW', 'name' => 'TAIWAN, PROVINCE OF CHINA']);
        DB::table('country')->insert(['code' => 'TJ', 'name' => 'TAJIKISTAN']);
        DB::table('country')->insert(['code' => 'TZ', 'name' => 'TANZANIA, UNITED REPUBLIC OF']);
        DB::table('country')->insert(['code' => 'TH', 'name' => 'THAILAND']);
        DB::table('country')->insert(['code' => 'TL', 'name' => 'TIMOR-LESTE']);
        DB::table('country')->insert(['code' => 'TG', 'name' => 'TOGO']);
        DB::table('country')->insert(['code' => 'TK', 'name' => 'TOKELAU']);
        DB::table('country')->insert(['code' => 'TO', 'name' => 'TONGA']);
        DB::table('country')->insert(['code' => 'TT', 'name' => 'TRINIDAD AND TOBAGO']);
        DB::table('country')->insert(['code' => 'TN', 'name' => 'TUNISIA']);
        DB::table('country')->insert(['code' => 'TR', 'name' => 'TURKEY']);
        DB::table('country')->insert(['code' => 'TM', 'name' => 'TURKMENISTAN']);
        DB::table('country')->insert(['code' => 'TC', 'name' => 'TURKS AND CAICOS ISLANDS']);
        DB::table('country')->insert(['code' => 'TV', 'name' => 'TUVALU']);
        DB::table('country')->insert(['code' => 'UG', 'name' => 'UGANDA']);
        DB::table('country')->insert(['code' => 'UA', 'name' => 'UKRAINE']);
        DB::table('country')->insert(['code' => 'AE', 'name' => 'UNITED ARAB EMIRATES']);
        DB::table('country')->insert(['code' => 'GB', 'name' => 'UNITED KINGDOM']);
        DB::table('country')->insert(['code' => 'US', 'name' => 'UNITED STATES']);
        DB::table('country')->insert(['code' => 'UM', 'name' => 'UNITED STATES MINOR OUTLYING ISLANDS']);
        DB::table('country')->insert(['code' => 'UY', 'name' => 'URUGUAY']);
        DB::table('country')->insert(['code' => 'UZ', 'name' => 'UZBEKISTAN']);
        DB::table('country')->insert(['code' => 'VU', 'name' => 'VANUATU']);
        DB::table('country')->insert(['code' => 'VE', 'name' => 'VENEZUELA']);
        DB::table('country')->insert(['code' => 'VN', 'name' => 'VIET NAM']);
        DB::table('country')->insert(['code' => 'VG', 'name' => 'VIRGIN ISLANDS, BRITISH']);
        DB::table('country')->insert(['code' => 'VI', 'name' => 'VIRGIN ISLANDS, U.S.']);
        DB::table('country')->insert(['code' => 'WF', 'name' => 'WALLIS AND FUTUNA']);
        DB::table('country')->insert(['code' => 'EH', 'name' => 'WESTERN SAHARA']);
        DB::table('country')->insert(['code' => 'YE', 'name' => 'YEMEN']);
        DB::table('country')->insert(['code' => 'ZM', 'name' => 'ZAMBIA']);
        DB::table('country')->insert(['code' => 'ZW', 'name' => 'ZIMBABWE']);
    }
}
